### ISSUE TITLE
youtube upload crashes when cyrillic text in description/title

### ISSUE THREAD

**Issue by baghdadbrian** [StoryMaker/storymaker#181]
When user attempts to upload a video with cyrillic characters in the title or decription, the upload will not complete, and storymaker crashes.

user can upload same video without difficulty, by removing the cyrillic characters.
[bugreport.txt](https://github.com/StoryMaker/storymaker/files/683006/bugreport.txt)

**Comment by n8fr8** [comment]
The only error I am seeing in the log is related to having an empty YouTube account name, which is strange.

***

: Caused by: java.lang.IllegalArgumentException: the name must not be empty: null
12-30 21:44:37.977 17812 17932 D HockeyApp:     at android.accounts.Account.<init>(Account.java:48)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.android.gms.auth.zzd.getToken(Unknown Source)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:562)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.media.MediaHttpUploader.executeUploadInitiation(MediaHttpUploader.java:519)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:384)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at io.scal.secureshare.controller.YoutubeSiteController$VideoUploadAsyncTask.doInBackground(YoutubeSiteController.java:194)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at io.scal.secureshare.controller.YoutubeSiteController$VideoUploadAsyncTask.doInBackground(YoutubeSiteController.java:180)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
12-30 21:44:37.977 17812 17932 D HockeyApp:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-30 21:44:37.977 17812 17932 D HockeyApp:     ... 4 more

**Comment by n8fr8** [comment]
I was able to make YouTube crash on Android 7 here:

 FATAL EXCEPTION: main
                                                                  Process: org.storymaker.app, PID: 3483
                                                                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=102, result=-1, data=Intent { (has extras) }} to activity {org.storymaker.app/org.storymaker.app.PublishActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.storymaker.app.PublishFragment.onChooseAccountDialogResult(int, android.content.Intent)' on a null object reference
                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
                                                                      at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.storymaker.app.PublishFragment.onChooseAccountDialogResult(int, android.content.Intent)' on a null object reference
                                                                      at org.storymaker.app.PublishActivity.onActivityResult(PublishActivity.java:167)
                                                                      at android.app.Activity.dispatchActivityResult(Activity.java:6917)
                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096) 
                                                                      at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by n8fr8** [comment]
Okay I have made some progress on the YouTube front, specifically related to crashes on Android 6 and 7. However, I cannot find anything related to Cyrillic or general unicode handling.

**Comment by baghdadbrian** [comment]
[bugreport (1).txt](https://github.com/StoryMaker/storymaker/files/695376/bugreport.1.txt)
another bug from today. From what I can tell, I'm not experiencing an issue with unicode handling, but with connecting to YouTube. I'll test posting the same 2 video stories to facebook in the morning. My experiences are on an android 4.4.2 device.

I'll follow up with Hamed as well, and attempt to confirm whether anyone is actually posting to youtube from the app.

**Comment by baghdadbrian** [comment]
were you able to test the fix @n8fr8 ?

**Comment by n8fr8** [comment]
fixed
